name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Build Docker Image
      run: docker build -t savington-x-backend .

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.6.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          docker stop savington-x-backend || true
          docker rm savington-x-backend || true
          docker build -t savington-x-backend .
          docker run -d --name savington-x-backend -p 3000:3000 savington-x-backend
